apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql8
  labels:
    app: mysql8
spec:
  selector:
    matchLabels:
      app: mysql8
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql8
        tier: backend
    spec:
      containers:
        - name: mysql8
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
          ports:
            - containerPort: 3306