version: "3"
services:

  socialnetwork_mysql8:
    image: mysql:8
    container_name: socialnetwork-mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    restart: unless-stopped
    ports:
      - 3307:3306
    networks:
      - socialnetwork

networks:
  socialnetwork:
    driver: bridge