version: "3"
services:
#  nginx:
#    image: kirillamurskiy/otus-clouds-2019-09-hw3-nginx-reverseproxy:1.0.0
#    container_name: nginx-reverseproxy
#    restart: unless-stopped
#    ports:
#      - 5000:80
#    networks:
#      - mydotnetnetwork
# nginx:
#   image: social/nginx
#   container_name: nginx
#   restart: unless-stopped
#   depends_on:
#     - auth
#     - users
#   ports:
#     - 5002:80
#   networks:
#     - socialnetwork
  

        
  socialnetwork:
    image: hl/socialnetwork
    container_name: socialnetwork
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Auth__UseTestAuth=false
      - ConnectionStrings__SocialNetworkDb=server=${SocialNetworkServer};port=${SocialNetworkPort};database=${SocialNetworkDb};user=${SocialNetworkUser};password=${SocialNetworkUserPassword};
    restart: unless-stopped
    ports:
      - 5010:80
    depends_on:
      - socialnetwork_db_migrator
    networks:
      - socialnetwork

  socialnetwork_db_migrator:
    image: hl/socialnetwork-db-migrator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SocialNetwork__Server=${SocialNetworkServer}
      - SocialNetwork__Port=${SocialNetworkPort}
      - SocialNetwork__Creator=${SocialNetworkCreator}
      - SocialNetwork__CreatorPassword=${SocialNetworkCreatorPassword}
      - SocialNetwork__CreatorDb=${SocialNetworkCreatorDb}
      - SocialNetwork__Migrator=${SocialNetworkMigrator}
      - SocialNetwork__MigratorPassword=${SocialNetworkMigratorPassword}
      - SocialNetwork__MigratorDb=${SocialNetworkDb}
      - SocialNetwork__CreateDb=true
      - SocialNetwork__ShowPII=true
    networks:
      - socialnetwork
  
networks:
  socialnetwork:
    driver: bridge