version: "3"
services:
  frontend:
    image: hl/frontend
    container_name: frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - socialnetwork

networks:
  socialnetwork:
    driver: bridge
