version: "3"
services:
  socialnetwork:
    image: hl/frontend
    container_name: frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      API_URL: huj
    ports:
      - 5020:3000
    networks:
      - socialnetwork

networks:
  socialnetwork:
    driver: bridge
