version: "3"
services:
  frontend:
    image: hl/frontend
    container_name: frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      API_URL: http://localhost:5010
      API_SERVER_URL: http://nginx:80
    ports:
      - 3000:3000
    networks:
      - socialnetwork

networks:
  socialnetwork:
    driver: bridge
