apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
        - name: backend
          image: docker.pkg.github.com/kirillamurskiy/otus-highload-2019-09/socialnetwork:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

  