apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    tier: backend
spec:
  #type: NodePort
  ports:
    - port: 80 # from service port
      targetPort: 80 # to container port
      #nodePort: 30475 # needs type: NodePort
  selector:
    app: backend
    tier: backend