version: "3"
services:

  mysql8:
    image: mysql:8
    container_name: mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - socialnetwork

networks:
  socialnetwork:
    driver: bridge