apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: socialnetwork
  labels:
    app: socialnetwork
spec:
  selector:
    matchLabels:
      app: socialnetwork
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: socialnetwork
        tier: backend
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: socialnetwork-db-migrator
          image: docker.pkg.github.com/kirillamurskiy/otus-highload-2019-09/socialnetwork-db-migrator:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: SocialNetwork__Server
              value: mysql8
            - name: SocialNetwork__Port
              value: "3306"
            - name: SocialNetwork__Creator
              value: root
            - name: SocialNetwork__CreatorPassword
              value: admin
            - name: SocialNetwork__CreatorDb
              value: mysql
            - name: SocialNetwork__Migrator
              value: socialnetwork_migrator
            - name: SocialNetwork__MigratorPassword
              value: socialnetwork_migrator
            - name: SocialNetwork__MigratorDb
              value: socialnetwork
            - name: SocialNetwork__CreateDb
              value: "true"
            - name: SocialNetwork__ShowPII
              value: "true"

        - name: socialnetwork-users-generator
          image: docker.pkg.github.com/kirillamurskiy/otus-highload-2019-09/socialnetwork-users-generator:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: OnlyIfDbIsEmpty
              value: "false"
            - name: Count
              value: "1000"
            - name: ConnectionString
              value: server=mysql8;port=3306;database=socialnetwork;user=socialnetwork_app;password=socialnetwork_app;
              
      containers:
        - name: socialnetwork
          image: docker.pkg.github.com/kirillamurskiy/otus-highload-2019-09/socialnetwork:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: Auth__UseTestAuth
              value: "false"
            - name: ConnectionStrings__SocialNetworkDb
              value: server=mysql8;port=3306;database=socialnetwork;user=socialnetwork_app;password=socialnetwork_app;
            - name: Notification__Provider
              value: InMemory
      

  