name: Frontend CI

env:
  FRONTEND_FOLDER: frontend
  IMAGE_NAME: frontend

on: 
  push:
    branches: master
    
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: 'https://npm.pkg.github.com'
    - name: Install dependencies
      run: yarn --cwd "${FRONTEND_FOLDER}" install --frozen-lockfile
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build
      run: yarn --cwd "${FRONTEND_FOLDER}" build
    - name: Delete dev dependencies
      run: yarn --cwd "${FRONTEND_FOLDER}" --production
      
    - name: Build docker image
      run: docker build -t "${IMAGE_NAME}" -f "${FRONTEND_FOLDER}/Dockerfile" "${FRONTEND_FOLDER}"
      
    - name: Login in docker.pkg.github.com
      run: docker login -u ${GITHUB_ACTOR} -p ${{secrets.GITHUB_TOKEN}} docker.pkg.github.com
      
    - name: Tag docker images
      run: docker tag "${IMAGE_NAME}" docker.pkg.github.com/${GITHUB_REPOSITORY,,}/${IMAGE_NAME}:latest
        
    - name: Publish to docker.pkg.github.com
      run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY,,}/${IMAGE_NAME}:latest
